export const posts = [
  {
    id: 1,
    first_name: "Bernardine",
    last_name: "Coldrick",
    email: "bcoldrick0@ameblo.jp",
    gender: "Female",
    ip_address: "239.40.132.130",
  },
  {
    id: 2,
    first_name: "Kate",
    last_name: "McCrie",
    email: "kmccrie1@gizmodo.com",
    gender: "Female",
    ip_address: "235.66.180.122",
  },
  {
    id: 3,
    first_name: "Kelci",
    last_name: "Lanfranchi",
    email: "klanfranchi2@t-online.de",
    gender: "Female",
    ip_address: "129.244.226.86",
  },
  {
    id: 4,
    first_name: "Juieta",
    last_name: "Weald",
    email: "jweald3@nba.com",
    gender: "Female",
    ip_address: "74.205.108.250",
  },
  {
    id: 5,
    first_name: "Marsiella",
    last_name: "Kulvear",
    email: "mkulvear4@photobucket.com",
    gender: "Bigender",
    ip_address: "20.36.191.18",
  },
  {
    id: 6,
    first_name: "Elianore",
    last_name: "Ripper",
    email: "eripper5@harvard.edu",
    gender: "Female",
    ip_address: "60.242.85.253",
  },
  {
    id: 7,
    first_name: "Livia",
    last_name: "Oldridge",
    email: "loldridge6@youtube.com",
    gender: "Female",
    ip_address: "207.105.0.156",
  },
  {
    id: 8,
    first_name: "Sasha",
    last_name: "Philpotts",
    email: "sphilpotts7@elpais.com",
    gender: "Female",
    ip_address: "176.138.5.0",
  },
  {
    id: 9,
    first_name: "Gregory",
    last_name: "Habbergham",
    email: "ghabbergham8@amazon.de",
    gender: "Male",
    ip_address: "191.11.255.193",
  },
  {
    id: 10,
    first_name: "Katalin",
    last_name: "Selwood",
    email: "kselwood9@newsvine.com",
    gender: "Female",
    ip_address: "198.154.193.61",
  },
];
